// generated file - do not touch !!
#ifndef DEVICE_IDENTIFIERS_H
#define DEVICE_IDENTIFIERS_H

#define DC_DEVICE_IDENTIFIER 11
#define MASTER_DEVICE_IDENTIFIER 13
#define SERVO_DEVICE_IDENTIFIER 14
#define STEPPER_DEVICE_IDENTIFIER 15
#define AMBIENT_LIGHT_DEVICE_IDENTIFIER 21
#define CURRENT12_DEVICE_IDENTIFIER 23
#define CURRENT25_DEVICE_IDENTIFIER 24
#define DISTANCE_IR_DEVICE_IDENTIFIER 25
#define DUAL_RELAY_DEVICE_IDENTIFIER 26
#define HUMIDITY_DEVICE_IDENTIFIER 27
#define IO16_DEVICE_IDENTIFIER 28
#define IO4_DEVICE_IDENTIFIER 29
#define JOYSTICK_DEVICE_IDENTIFIER 210
#define LCD_16X2_DEVICE_IDENTIFIER 211
#define LCD_20X4_DEVICE_IDENTIFIER 212
#define LINEAR_POTI_DEVICE_IDENTIFIER 213
#define ROTARY_POTI_DEVICE_IDENTIFIER 215
#define TEMPERATURE_DEVICE_IDENTIFIER 216
#define TEMPERATURE_IR_DEVICE_IDENTIFIER 217
#define VOLTAGE_DEVICE_IDENTIFIER 218
#define ANALOG_IN_DEVICE_IDENTIFIER 219
#define ANALOG_OUT_DEVICE_IDENTIFIER 220
#define BAROMETER_DEVICE_IDENTIFIER 221
#define GPS_DEVICE_IDENTIFIER 222
#define INDUSTRIAL_DIGITAL_IN_4_DEVICE_IDENTIFIER 223
#define INDUSTRIAL_DIGITAL_OUT_4_DEVICE_IDENTIFIER 224
#define INDUSTRIAL_QUAD_RELAY_DEVICE_IDENTIFIER 225
#define PTC_DEVICE_IDENTIFIER 226
#define VOLTAGE_CURRENT_DEVICE_IDENTIFIER 227
#define INDUSTRIAL_DUAL_0_20MA_DEVICE_IDENTIFIER 228
#define DISTANCE_US_DEVICE_IDENTIFIER 229
#define DUAL_BUTTON_DEVICE_IDENTIFIER 230
#define LED_STRIP_DEVICE_IDENTIFIER 231
#define MOISTURE_DEVICE_IDENTIFIER 232
#define MOTION_DETECTOR_DEVICE_IDENTIFIER 233
#define MULTI_TOUCH_DEVICE_IDENTIFIER 234
#define REMOTE_SWITCH_DEVICE_IDENTIFIER 235
#define ROTARY_ENCODER_DEVICE_IDENTIFIER 236
#define SEGMENT_DISPLAY_4X7_DEVICE_IDENTIFIER 237
#define SOUND_INTENSITY_DEVICE_IDENTIFIER 238
#define TILT_DEVICE_IDENTIFIER 239
#define HALL_EFFECT_DEVICE_IDENTIFIER 240
#define LINE_DEVICE_IDENTIFIER 241
#define PIEZO_SPEAKER_DEVICE_IDENTIFIER 242
#define COLOR_DEVICE_IDENTIFIER 243
#define SOLID_STATE_RELAY_DEVICE_IDENTIFIER 244
#define NFC_RFID_DEVICE_IDENTIFIER 246

#endif
