// generated file - do not touch !!
#ifndef DEVICE_TABLE_H
#define DEVICE_TABLE_H

#include "device_identifiers.h"

static const struct {
  const char *name;
  int deviceIdentifier;
} gAllDeviceIdentifiers[] =
  {
  {"AMBIENT_LIGHT", AMBIENT_LIGHT_DEVICE_IDENTIFIER },
  {"ANALOG_IN", ANALOG_IN_DEVICE_IDENTIFIER },
  {"ANALOG_OUT", ANALOG_OUT_DEVICE_IDENTIFIER },
  {"BAROMETER", BAROMETER_DEVICE_IDENTIFIER },
  {"COLOR", COLOR_DEVICE_IDENTIFIER },
  {"CURRENT12", CURRENT12_DEVICE_IDENTIFIER },
  {"CURRENT25", CURRENT25_DEVICE_IDENTIFIER },
  {"DC", DC_DEVICE_IDENTIFIER },
  {"DISTANCE_IR", DISTANCE_IR_DEVICE_IDENTIFIER },
  {"DISTANCE_US", DISTANCE_US_DEVICE_IDENTIFIER },
  {"DUAL_BUTTON", DUAL_BUTTON_DEVICE_IDENTIFIER },
  {"DUAL_RELAY", DUAL_RELAY_DEVICE_IDENTIFIER },
  {"GPS", GPS_DEVICE_IDENTIFIER },
  {"HALL_EFFECT", HALL_EFFECT_DEVICE_IDENTIFIER },
  {"HUMIDITY", HUMIDITY_DEVICE_IDENTIFIER },
  {"INDUSTRIAL_DIGITAL_IN_4", INDUSTRIAL_DIGITAL_IN_4_DEVICE_IDENTIFIER },
  {"INDUSTRIAL_DIGITAL_OUT_4", INDUSTRIAL_DIGITAL_OUT_4_DEVICE_IDENTIFIER },
  {"INDUSTRIAL_DUAL_0_20MA", INDUSTRIAL_DUAL_0_20MA_DEVICE_IDENTIFIER },
  {"INDUSTRIAL_QUAD_RELAY", INDUSTRIAL_QUAD_RELAY_DEVICE_IDENTIFIER },
  {"IO16", IO16_DEVICE_IDENTIFIER },
  {"IO4", IO4_DEVICE_IDENTIFIER },
  {"JOYSTICK", JOYSTICK_DEVICE_IDENTIFIER },
  {"LCD_16X2", LCD_16X2_DEVICE_IDENTIFIER },
  {"LCD_20X4", LCD_20X4_DEVICE_IDENTIFIER },
  {"LED_STRIP", LED_STRIP_DEVICE_IDENTIFIER },
  {"LINE", LINE_DEVICE_IDENTIFIER },
  {"LINEAR_POTI", LINEAR_POTI_DEVICE_IDENTIFIER },
  {"MASTER", MASTER_DEVICE_IDENTIFIER },
  {"MOISTURE", MOISTURE_DEVICE_IDENTIFIER },
  {"MOTION_DETECTOR", MOTION_DETECTOR_DEVICE_IDENTIFIER },
  {"MULTI_TOUCH", MULTI_TOUCH_DEVICE_IDENTIFIER },
  {"NFC_RFID", NFC_RFID_DEVICE_IDENTIFIER },
  {"PIEZO_SPEAKER", PIEZO_SPEAKER_DEVICE_IDENTIFIER },
  {"PTC", PTC_DEVICE_IDENTIFIER },
  {"REMOTE_SWITCH", REMOTE_SWITCH_DEVICE_IDENTIFIER },
  {"ROTARY_ENCODER", ROTARY_ENCODER_DEVICE_IDENTIFIER },
  {"ROTARY_POTI", ROTARY_POTI_DEVICE_IDENTIFIER },
  {"SEGMENT_DISPLAY_4X7", SEGMENT_DISPLAY_4X7_DEVICE_IDENTIFIER },
  {"SERVO", SERVO_DEVICE_IDENTIFIER },
  {"SOLID_STATE_RELAY", SOLID_STATE_RELAY_DEVICE_IDENTIFIER },
  {"SOUND_INTENSITY", SOUND_INTENSITY_DEVICE_IDENTIFIER },
  {"STEPPER", STEPPER_DEVICE_IDENTIFIER },
  {"TEMPERATURE", TEMPERATURE_DEVICE_IDENTIFIER },
  {"TEMPERATURE_IR", TEMPERATURE_IR_DEVICE_IDENTIFIER },
  {"TILT", TILT_DEVICE_IDENTIFIER },
  {"VOLTAGE", VOLTAGE_DEVICE_IDENTIFIER },
  {"VOLTAGE_CURRENT", VOLTAGE_CURRENT_DEVICE_IDENTIFIER },
  { 0, -1 } };

#endif
