#!/bin/bash

if [ -z "$CONFIG" ]; then
    CONFIG=Debug
fi

export LD_LIBRARY_PATH=../../lib/$CONFIG

# valgrind --leak-check=full --show-reachable=yes --log-file=vg.log \
../../bin/$CONFIG/stubserver -p 4225 -d homestation.properties
